apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # after cert-manager CRDs land
spec:
  project: default
  source:
    repoURL: https://github.com/nameson2672/polyglot-sre-platform
    targetRevision: main
    path: platform/infrastructure/cert-manager/issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
