---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCcT4jPTnKwuqhJvMQbr1QxH5DAFW23Xa0QXScDlaAJ7PZ45dOVLCLhwN0lzIQJybB3eXAVKwT5wpF0CWbHWYUuWiSSsVNIjB9pBg+by0NrKQu31lnkRqjMU6U/xfttF2AGSVDT8Ea2dxoXJMR+3MbRm4rqiHOVA2X3MV+zv1L/2A/0N25HZTnfk0bLTuch432gDD/Qdeh+6h6aVpMy1dJdklWljzaWBPOjaS1oCQA8r7DImKKL6SiZVdetaszerSeVzXUrSXzgyinRWPSNAzTviC/7MHDNrEu3RSm4H4cr5RhHxcPsbWBh+8Ayzy3HH+HvPkVVzUdMYfu7CiuE720uDHwVhuxrvQYXAJ2NiGUE8FVak+DGGDtLPNqf8TLWvsEU6BO6jN3rJPkdDS33WpGVMWDb1L09UU2OSW3YruHGnL9JPRwQbiDhNEt5GY33PL8poPXIE++ZCfgV9Lb6/7C22q2ZmxF8ZFUzvE65qZQTHrFT+LEAs30ik923kRvPxP6U2cnT2dEuo/WUxP73wTmCP7PnQgggH0Fhg3914oLxZHjAVhwlyT7yK9UT2MzzT1kai4tVhC/AM6BmccHCFPeyc0kH1P4BkVlW8W5LQUvjZRl1KtdcuTl1LTIfcUEGSMD8+D2zFosM+5EFF4UHj5qL8GzN0SxnkK8ajlHeFZt+oqMW3FhrW0LTehTZHt3Ia5OxyjSJRkiuIek=
    admin-user: AgDKZEEKPHXR7wr5Odvc0BTLZp0mlcsDAC2RaFmzSbm68mNBr8qXvlQAq1L3v1F5jKdKgNl9bWey2v1XuGyUngn4cjBJNAna7OY4lkFuFwLOLj966carhHrreqHX9bTggv1NcxgRhOO8T7gEiUyo5N6VJQ9kopQej7iGWvuNzpDgqbI4Vzxx7tpIU5aGkJxKYen92nzItviYMbDyTK+R+oAwn2x5EyN5fG+KoYxmEJHZlBy978vwiWXdIP30eON9mTEe3TGVcnQ5+wRXCcCzJwk6c+rcTcbr87l5pRAy3SkYk3ZBmL4UmCMEUzbVSRDwotL3mMCYKxng1//ATohIAQlrW5iaNcsBTu/NnMQAcRuPMWVbtYPNQNojg0QzPujpEXHdUzc+QITqYsw8gRrKw80ff7LfRloQdhRBIHWnq6hMp82OaPuYM+SWpZ8sRWfRU2MLMCbGZvZduDfk3ggCaJsdiHWCpWlNtqVekjKAkh5LHc6Fbl6CqZBQxbzmi1BQtY5sHuSGbtaC/LP2mS7o+GCzQ+uaIUoI3xr8z3WG4fWavZMuP5OrXMxZkNiSi+iP7ADFWDmok18kxeIq0cRoHe176xuZmPadu+HbguL+kizMbD/EAC4q5KM/P+76Ok9CXPKw9fnDxB8edwqQZLEJCEqGsUikhRQEURz+ETI9RXIMlASHWK3dgYGoAbf0rhoxEZUq5czxDg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
