---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-credentials
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAKDWzwYUpbdn3YZhBEVoVw6EPwLfwB+i96FD2OSiFPCGx7T8HqVMXaY6eBadqAitWw9RjmLiVvKe86rePIlI8lxZAIeKl1wGuGqMtniUcyTj3dAeh0hAbDGdnCVBs6ze9yMdU/U3URtrysCadvPvu5aqNuTXlQgOnAXwpKqnTAGlNlTDPhf/+gVMUpYVg4GAJTl94D/HKms5daV/g/v825OjkdgETk7mhAIJB3goyzCbfo+Vd7DkpcKjVvaCrh7tz8q+Hgm3G6g42F8Okw1R0c4+orqzvpTQBhd20XS+M1AA7xOSdUfndvxafXQJGjl4l+3/gvVk7RY7COXN+NnR4lmxF1Js7JmuA/vfQv4nEQyEiC5hgtOaFTuOFoPZA/CFeha1vKAq4r8D519zDxF9dVIZ/YI1QKsUtUGM73JQcWdC5k1aWKJmS7edaypH9Sd5sfpAtJ2VGFKjcLFHoRjifUzCRE/+ULEuAxvZMtU+WD66LTc3sQK4sS5/s8CgjVUX7TLr2RwWljwKd+U6r5zrFisNXWJAmF5gXOcbEePCedmLWdT84GuHKRxWqVm25JuYGgM5ln3WE5a5abSrSxSgx5jOTVrUeGIXmuvs3pdCrarSdRCWC1o+OeNbPgCMus0QLufwLTQ47Rkz+Q5JbblGXq8ijeVXlK1I1ITpCeZLy7UFikigEORJ5ZcwmAFeHPvR27XyKLmhEnjvR9/EfbABmiXc+HKA==
    AWS_SECRET_ACCESS_KEY: AgCF3zuqageWq+yAUWhlX54aP2ky0rRxsNAjf3RbPl6wNbgCj5/riqzPT0ByBFoN+2RMsQUm0tyOHzD6xsKjX7WavaiHLa+9auStau8yX6PgbaoaLgNE85zgWk6r5WxkfrUcWYE5Kx6zew9p7b+jZMlfehGVvcO+8KaoZbxWA3EQWdCo3F+OELUVC1UOnV5aMxNPEaww78VRvWzE9j04LQJmYF9pe6kBrsWm6FLmnpx7lugnBg+Nlxs/HzZddmVM3ufZ+DTRIK5+VikyOZPd7YNEMOlM3mAZGuV8s5SR/m+x0YLzoyvu1hUHXruu2rLOfkZoQlRhNcuGmZDWJ4MpiqnvLX7tWdZ0lbDry5XG6dsdUnikNrhWqcGYKVdqTHNSxhRvdqlNdWDMCOTvolHjwMIgugztyVz9yj0l5p8xm2fV9BDty3CXJp9OYUR7jqpkE9/7xCNAlP5pU6DvwE8Pdv5NX7DUgnM0M7EWMERbpFeboFvHS6WLBAiQhKbPdsDn70qaZrdA7KIAMnRqSlPlUxers/Ustq2iEulYHoXbr3zYQ1VtUTz+3rwo6kYv9nD1aFUdBipQV9AUA+YFU3QxcHFIy33E3U/gA2aftc9XyPkoU7Ll3T87KE0Z5/A5hrCziapZ/XdS4KED+JolSc3Wkclw8sOPoh8ZxV37e3VBcgsZxbvF/M+MlVw7GDFwhrJwGyIySovWPJEkWDI/x/nq+of2S3cTwBEIe99sMayZ/Z3YRCSeRu62NTOy
  template:
    metadata:
      name: loki-s3-credentials
      namespace: monitoring
