---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-api-secrets
  namespace: dev
spec:
  encryptedData:
    ORDERS_API_KEY: AgBya5Sz1xcyFMPHPXz9OCE6Zi8f7WFHRPjaXP6AFv16U7vvSQff7GdGmCBGMnuvlKWxEIxLWY8SJ16S1kDaLeO7q9/OrY3iBm/P5WgWnqILyTErrM3AOoM2sukuIaqIvYYDmBssyBVZiUE4SwKV5zHk7DCVJZgy59mfRc8BdiqCMI+wxe4L9g3Ju25G86BD+xiOLxtRZSC61DLyLVrT5UxgbczFqyOTe/GHJmKjHL6RKuWhl08Clzx3atHcsQVt6ORp3S/x1b4e2yk5YTkNUor6LrqQIU6HhuaenFsh2xRaE4U9EV8EbLGZtA/+ku40rqoqqqi5kcPVL0UHvlX/v2M5/Rt+Ibs4+4XOrtQ24B5SEf+ONM95dxIuAD4oBGmv+IrTqZsrsPZKN9GsQKUiRishT8ztKI+jL+grb7V/J9jLm+OH4+XSykdvtBpD0OJtS/zdhPdfqeKfZZJaP7NirmaNGxXqxQ/acixJCDBJ3KL7yBrqE1EYzkFwx1heN6R9GQJ9Gd+FxKbIBa58055PYgWDckHNLM2ZuBmZ8aPFMyPJBh4H1Fry+YIiK8YR8ZefUXJWpdj99F9K9ifX17+TPBrKnl+EqPVPp31XOn91/9lOo0XElj1+QV6s30OMGqijhr2fIsiFZv2vRP6W3nF+NlIxSrpZaObAWXB1tUOz/vmjyg5iLm1A20++y0dLR5hEDCFGQ+M031weH5slJ8Dj/kN5bUbvOJZ3fwV7HBrAc7pD71+BKGaDIrVFYC5habzT8KoRunYzjGcK/1H5n2NmtVLw
    POSTGRES_CONNECTION_STRING: AgA95Siz3VyYAzbZNwYHdvcmQSHf+PhZS8QmT9jfbQyLXDoYs1ikjEUrsOvzi6VULzr/T0eMzsPu9SYECYPHQVF7FtrbPk6OLXEC+x522KmOGO7QpcCuieQ51oQKxEF+4MidF9hVZ/wVkYku7VsRLJtkGqM/KKfnosKqB9q4iu1ALkuxtH677QvDxRWGoJC6Rs8HH3O8ZcfNh1Q8YVY5z8ta65NmPu0tyJAJct62ecfa54hCpZw0BVzWoMsQmr3PN/2rBvtLo+JmMxOxoyL5XEhpGeamHlY5eGlE9MKVMdb61SEdMRYKr3lJRAh20yMpympwHrjVNMmlyQDj4WBa1aDKU3G6fPcRKfcapE72hr02vUqVwJflUcqMiTTfF/rQpP7l7uxWVmWkt8fn23i64F5uEnIxwzbDAdWN/GVSMK/sZqWun+BcwuFeuraDHvUR1MMU1cAQebxUBnrTUkJFRHUey/v1q6I+KBJ3YbUnIAPutVXFss0JxQnuYayu6say7ElkMFehqn2XLZ6pK/778+L5Fw0x1nyYKe0MrqFu4K8r8nYryGfHdLEd8gURpnn6k7lD4XCdKZBDhfVinr65t6FX6xL5m3Y8eS23+OfnaN3hMHF6la455fAO0xwxWi/Mt462Uq4c+BmQnEFitu0stwL6m51/Teg0X3C6vgTIwmPMI+FdlFPIkTB0YyXji5CzOmy6VH3qyiUhQVnLfxznJ4/y0MVth5eVYL0cM+FJUIj3yKhUNb/er1Vjv0lJ/c/YFazWZRmgHsuBHxSV/07UmUnq3uIXTN8T139UzCw4C+Fl01KATI6BWrJwTt/hpOT9Kf4DmvPb0nSwQUi+LA==

  template:
    metadata:
      name: orders-api-secrets
      namespace: dev
