---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-bootstrap-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBxzAup7B/EsecQAY0pMdKNmaVNYE7xdAC67aQ/bV0Ky3pWSk66fy0dlAYvp3/pngi5+GxAje/Tv3+J3sLu+oIYz/DBSeYkjUjby7fSFwul25ZBefnAF2KYfK17+cZQiPw95D9f4rujrGOT/omwCLmk63WGa6DvwW39m1q4RP1539UkRIzTRBjOYHzlZ3jlHATx43x6VtIuF2uqU58Ec09exghCOAGZBUzn3B4rD45T2nStJxXPmcByfVw5nMWfKvcES8Dbv8T7tYSgUqlWPYelgV5atuBxmnsuoffNn5sO2WQMTc6garAcdbhzd1u1vLSlDTGyI2k41zW1oVi91On8NpcaoB2Lv/YifPUrji4K6p5oVRINPHlEvDSX2kUCCEOS0VvF9Ml273Cnv/3ECmFHbPX6KWM+cmgwysQDJyUY6jK1AfclTRtbfpM8CnoQDOK8XrNoto6+SJjqB/66bGAIxZ+GoyE4JJd4SZhnR6fJ9uwxjIqTtEKOgSYf/M9R/130Ae1RN0z14/F9Zc/kWW/uGfiLTM+Mv6uosks5uCO/v1YwCc/9xrRpy+i1UEHDxuA0lJG6jlcUwcIyDyzmqcd2rn88CNItO3nVQCXuEXzNFdwvAtXddYYaqkERuzprlHRYM/Y7wPTsaoLh0Pna+KfsNxT7aLQsYumiUULsrNBSEGiYS4ED4buWrKI/qqF1IVvVbHd+nWIaQc32caI=
    username: AgDE98KIC2sloj0pyhrk5/d57X8L+tAmoV0TAWxtNIcZfO0d/q/2ypFSqK4DL4e2p65mftDs/qqVx++kvWiOwb6CosG4HDh05WLYtBIw3juSS45XGAn6ciZoLDf8W5BJDQVNt6ASgENTI8sqx2/BEQRSNgHfcde3Mvr5L9kbHNnkqCRXX/tpQcLDGaFKwy82z3nalC2q6T6JYfolpWeV6zdGdNACBmCZ1QN153WZ1KKWtYPpCejwz6UY4BEHES59Agog1X1DD22tfrYEGe5uYA8fuL7cXPnmFUqrE8VbW0prAWT/aZQlgf2uXYDQyHrXgCoLmMykO0bn5i/Z+CSTd+NeQXsaY2A6hs3ffwWb+zvRb0UxHRvRvAUOsi0bM1XWdc+CzjBaGce6krbQIggOjU/bOCUqovzwbAGy+4Ph+M8evE0Ve9RBL4QUnYG2OZRgQCqQpyV7xcNz+rFtmCzE35dwfwPN3jPyZ1oRRB/UoFrrpG3R/sh0SaKQyFXx9oAWAelbxI4qkeAF0ETiW0PMXiGoE7aqcmSwpi2dRJlSp5a+Vn5SW0x4Fx8HFELZQbwUMk6F2VqK+wl5Npk830Jh3tEv8x1bWre6eMQtfPqMCDm7v+4Ksf5lY9dvnMPHLHyQr0wFywhVzDGEgHHng+6F/ZGWwNReJyPrO2eU+VFtIWp5JtCO9BsU8BP4d5iVgvGEaSyImk5zmuI=
  template:
    metadata:
      name: postgres-bootstrap-credentials
      namespace: default
