---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-bootstrap-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBNWv2VXo5UtlbN9t4VqpzaZNCzXHYrkMhJhj9PPZqv/K+XOkei8SH46rCJnq/+68Tgx364zz+bYJKuy+Op+V79gsTdpDYoG/E60JnUpNJ1VnnEZfot6cds6/kcoIAhcXuYA8sK3zXlLd9Z/BFtTLKc4ROwnYWxmcqq8hf8U4IcE25dpNRcywCzOgMVqjgpPWuZyx9DX6uM6ZvsqOVQdAiEsa1cq96WPNWUaoDy5/3UElWgK6bqLV39tlihSoNg10Hf6SsMhm7lq+XZeXsMUnqziAB008c0OA2PL5LyAU2q8HR8tVhZmjPHnGMlhan417jJTtMkyrX0Gy4V5foV/9O5Sz/FZKiW4HevpRjKYIClGj502k/nyDVuDI6s+qv4i8+6+45SqbVxlwazld0k6RqZ7WvR+a+TV8vPZuOxOKgP87is+koyAOQC8RoMjpgZ6vkmhRzAnI8icvm6Tx21ElliaZg64XYvDzGX5LgHQK6gVIO9iyJH8Rywm6tZWeobLEDGMhy7eRgcdjv3q02SMoNUuPJ4ItFGOwj6yzfPqXeadnnuVeTJF4+RbLDyNMplK2NOYfdfvkA0HaobZXkXdjUQjETP17PrltOGH9QVBveGMexSAEVrueqNejDNX9Y/I51gQgJ61dzM3oVkgwl91hoqgkaieHYcweswYcGhk2loctlUdpuqPRirsKKbFoIk9MbknVcntnfbvsTP
    username: AgC5GCEKFGwr+/UvYxUBNuX8Rmgu0tvCb1TUiRjgJDou5/gYLzEhMC2FBzXvYNKGksPFnrxl6K8VOwyYESS10LivNpbybehzkIHSwsRUgT/aOTrvkAOOojCen5fTnuGS5CLBDPTH+2buMbD+Ob6PmqE2rdkbM2hJNfgXSLUYyjFRyx2H4RlC2uIobqEfCaD4fg3I/JQ/UV3IfuydnP396Cb3g6saw9H4aeSly4+PcWv+5q2E2r/Crw0FyTOSqEuOXeps1zs2SMPBeIaXT65gITRO6WhDvKPf0x96UUgBTUzObqo6dtiwrsf7Ut53c7Cq6WZcHiYh4GkfICNNnhyMxQU5u9nJ0JhN7fsIK3iPojSZP+/UipP0p/Tl2sDCPzlsSdKnSRTJZfyUl4A3EiIlyjRUZLs5U5GqJcEZI9ka9t0GbF7guhsRqtQh+JKgjZsBKTtEhgTbOVsRk2RHyQhuY8fNmF285QaI2k46dx+Pc0mxqzeqDcUvzIEdLni7LCMtGT4JOmqczvuseqj3HK+yr7yc7qOb1/D8hdX2+QyoGGEFYJERuQ2TgRiQPUXGH69V++8ey7t3RtnzUSU6DxVbfr+8gKUE2v61QgvovM4DumlzFlwV7zg/LiebTJOJm0JsltlcGsazLk46vJWWQhSaRnNDU53r3mysKU0D3diqS7xn1hMyRS1VDnjNk13qK43+ADq64uECwjQ=
  template:
    metadata:
      name: postgres-bootstrap-credentials
      namespace: dev
    type: Opaque
