---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-bootstrap-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBU8zeOOEShV5aRmgqOwHwXkhMtLaC9f6eAfRCnay8wf1hTuHuRqPt0e4jLeIgRF7iugnEYfOVu2oPQEADKSZtSXA5ZFAehb8AUzDUHSbksLmEsBHHHVS1VCUZrr0mvWZDoL4YpHKtdH6TtpyO28oPGF++W94HtHyZm6lF4RI0SXZTJsTGjm3d9/MkAk3pAun7LPYj2+gFd5uvN5m5qDngw5muCGu4ZhUyV/1mwXrdQom9/B00zdoszv2JCdiJU46nRmU8/w77UQgF/LeNuGcPMlQwkK3I4oAwCIpjW4Iixbr22cOOoFBJlK8/AJIlf0S3f3DDQ0UxtHfFowh/9q0Z9HhK6CCe8MOjCfWa/N7Yq5dCkliwXv6ne3Ev2Wno3Wlg1IYLq8avWgnk+IaNuQVrg/Z0QDvBs4ApcYIRCRaoQh30wrU/QkAa/cZGxqv9aBXMVsJUxsEm4L+ly3PXVzbgmo2CCK0bwBijZ3HjuHSoNXQTTeJqcAE44/MLY75fjqNwjrbOrGJwJfp1yLUo+3dtqtL/nI+Ss6VPwzC010TcsOCcRHgxEC+JEvge9A1U7ItkNh9Zdtxu4h9fkHJyyb4196WeYEXyXhqCbiFcRblLP7z08IokcHjP8/k9eQUwB+9zt6d63fDjOG/l4Ys668bWNsYDJUboBL6T0UkgzWlJt/lUlXvjYW3G3gsxv7MobFFZQkWgSStm7RnI7/k+IP88z
    username: AgAW0uah5cjKdm2mpT4PWz0kEtKsajacR44yyJGz+ORvl68MF9xH+bh64d1rLz6Dx/ufTmvWZ6GNXhWfrF5LY5lk4cFk7RRpW+ojKId28KkBYhN0ls755uqVJk2kTC+6p48dUYEcogx70Sh9P+5wrLyhUFl67DEZayT/oOQakReFDugCNAfUKUa07XtZ12g29MO8VUYV2JpXzW3Ku2r3vfK/mS1Jt2yz9JvqPNq/MNRQLcF1xD/Ldxk5f5sseiiVNpUKKNpgwdqeQ6m5R8aHhwBvy87cY39lOoU2s1kgfcqS9ADQxdT2pL1PA7aW9Q7mmDanQcs79jsH70zGV/ExJOhxYetlEx9FSDC7mv6SRZLCG7rMDhBnPEd+2Q305+Y+gh968mZfjFlVnYlwp29d93JN4CA/C6c6rgVufoTp8x4r2TalFIa6dhqEYGo8pAGZK5t0QiXJtiltwnjQ5FiycQezJJjDNVsDLRbfAsnaa1xPh9CZ76Vh9UNEc3r2uq1fYJT+1bMaJ7mrINVFGjGyzgJ/0pE/A/GBRUVD1V8dSEcln7Dbusemx0kpHJQhmCCO3btjMCCoRBHbSoPK3KcpmQ0meBWHBXpbjRCvVqZkCxv3qhhXcgJlJ9TJzhSa8YsmyICFP9d83u/dIRGA03b/TC3CSGkwMAsgcaVQ4iImdRtbWV5ACJVY0QF7uBESfQ0ZOZs87G2WnnlM
  template:
    metadata:
      name: postgres-bootstrap-credentials
      namespace: dev
    type: Opaque
