apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: dev
spec:
  encryptedData:
    redis-password: AgBNerNcukj37pTwpZ6wkhdu/WhJ1TWtCiCnhsujDwT3BNuKAPDyHn9OyLZzSUPCUXAzY9MX2Baop6tZ7O5jdwV+BwA+6FJKdVmtXlXk9HUvpKYMtHSpl5Pplxp959S8RKa7zSdjP2dKnMH2JDyyIQQVxXRgjkS3LDIdDfSDusrP7s5AgVppwdAIOdslfP6pKDjOIruI2uRR1mzngFLVU15HP9VzEwGpRERmQiATMMVVqeIFVyMU/kZiHr2/f0uxWYGKPAO5mDI6SEmaCovYh/BQEWrJ3/0Ld1xdEbV0fmNQT4Mwlahm4hhbIBRRa4hEUOXEgyD6Dejf+V0++91sOkqIa3Iv9nK8f/Jd81c5MCU+xaYHsFuxbY/brgbrTcZTjd6KzePdqL34KmWaTYkRXOYLjGptrEgTh/V2WzY3zcvES5qdOxaMOXf5qAGt+YfjV3f9JEaNmsHuIbdBE3S+/KO6g5mwaRmvxqf0xrzoi8dG9eCc58i8SBz1+PW/6hgwx4BGZOkEjn1NF5NhR5ek/MpUdMEKffeQxcgEd5Rv0QxwP46nFhDr/0UJLR0dxSsl/phu8VQFaUjzv9QfTGGtPnYBKX5cVk81zsdy5AyjxC9eCK8B5CgOxLc2WxGoeqz5KrQsPGEgD0zIibHfNDxzBZDjzbvGM+WHHD1xKrFnKYbPCH746sf+w/bVJ0c1Y6IAQcqVP9+8Fu9h7bKOAKWnw2vkaR3RAgxnvA==
  template:
    metadata:
      name: redis-auth
      namespace: dev
