apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: dev
spec:
  encryptedData:
    redis-password: AgAe9d4u7syNmqbrUcVvQ3RsUVVwxLi/DuA19yUuBocsUw27m9GWMryK2/Umb4pl67aRORpkq3zD0/0ET7Qv/UiZs0+J8eqo3GMjLA13sI6jVksqX5ZAhAfEpN4VntFb/qx0TSUzgwYGZUIFZSyxldCHAdT/vAFSrS5WcCJuGHCh+AMK9GoWHVtJjA9mmyoy4cBhqTTCjtXy8wzUjFuZq/+4LyZ56uu0DLmTfcEaYILoh/UgCrJCUFxXlIhQZcJ282C9LbF69dg2kJwCXf3p9ViEwV5yLcnqO5p9e9B9rBiaJMn59fMv0sm05FcHa3LTpa0Fbs+SQnEDg84uRST/4IBskQmwVhil2MlOTj/d3QvWcP6vIuM7uY+pNLFnSFRhHrS7O2vuC5IR+G6HfJydjb16sHM67hvV9Oq145SEvvbSXuKdSxYj3A1eR1Ze+Wy+9RdQLV83CAeh01ZejVeiDpkD8Z1qB2PPKi1AYxnb0VXlWYyILUD8xkmy03FOOZAJRcxEoIicCGMsoUfuikwWiVRwVkLc6GvPcsbjiVlBFTdae1ei4R9Bs9/4OvsWATN3Z3Ce86cXeyNxEKMighmsh++k4LpUMB1AXYgJUNpT30JNel64+f3vxMLd4CKIfdRKHj1JI/XRwmfenzvwcgCFn6Lyz9AOgITUfPbaTJGW5oOQiejjC50F3tP7j/M/hyS6Gof7uKImYlpY2cZEhH61zzk=%
  template:
    metadata:
      name: redis-auth
      namespace: dev
