apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-url
  namespace: dev
spec:
  encryptedData:
    redis-url: AgABgDhTV/Nmbp/jheXo6FyyWidpeO1Av7oi9PvBKy7aU7qgUJWaeWPdl0C2Xm36znaDgfLx1mvsWwj8gyt2lNzyqbR7dgZGefft7TEbBcaZ9T7ah3l2WoPhOl11ET+2DMZ1XvxVZi0//kM/0rqnjNvC/VIv5ugEPcmPvlf+qruZcU6GGFXojZFfRrw6dzUe7Y5gAf+BN5SteKQPbHKYCUvdN3iGqoMdNLRO7k9HSSDiwzi9TdOe1DwkH0ylV1fRTeOb4iXhrecsCD8AV12xzSghWweoWxjEJPAMDy/32S7UTe7ffJIvvDvjFagqOdPWytemxFTGPt75mVmieAfXGZOaLYbDTUOQU43oHbCoedqUqxSIlRkRy8oYBEXrYDc+v/iOVRJ2p9AYwDyytYHM+R5hT6KvgZ1/vykimKKCtGbtNV3/jt/Am0n0UxykEQLMVYupng7ePF3TNS19e88YZ4R+LDfX9usxraaU1LzSOBS13/OoCekvYTWhPcurLaUEE1O0veC5+hiWsJvce5KNTdgMNyCaYMDW0GyR2CFwvek/TpOPFDJPEsfzGfFY9BHsut4QilzTBNWLxPSTrALMgIJZuBmN/nAyFS9kNcXaGShRZRVBqQaTYIaMeAroQROMKn7Pxx9KYRGZ7J82x4MJIZEePSwh0f343cdzVjTe4euTLswAMIIsxMQoxUapjKduVwgAI+4Z17Dh1rLZ9A5kAWQcFZR50ABbrmuyeCkFC/5UXg0WB2+8aYLlwrOhUNLsX5DV1EKmEYG/llD6ILULY20QFQG/2Q==

  template:
    metadata:
      name: redis-url
      namespace: dev
