apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: dev
spec:
  encryptedData:
    redis-password: AgBrZbt9ZwgvJZeBmQROiXg195FRMWRoALZTRhLZ19GI5yXIGUskdGcs+j8fHctouY9YpRNq7BzHCoV1f6/zSti3N6t3KHt870pkogkQ86gF2Bu0BXzxqBwP+oJYrjonojhiZbilCIU/9ceytbbhfjMrGajfFBLDD77Zf0RNO/ijzUlW4FWdRMf2FP6GuUm06mNMtuluQ//5RExNenHHY/rHZfxGejGAsHlruc7awkRfMBT4LIycmp2gHZS7pBUfhKoJL8wluLFTsVQhFEGXLtsJaZq0GdapYOVbg7ueqzaTdE1FFcC9r5Fe7NG6ZFo/5LMdcypI1jb7pU/2aZO3kAXZaOIKXJMrsNJc8eLcMeiWHIm0NiYJWA7bCKfQT5G0rH4wKBsUpucTKlBLvtU5CI0DsKGJTzRWp8o0KJoTa/IyrS2I/YZoqG3UINxz/I21JnCM85q8Ju0SlPIVBkJNUXo7Kllt3o6m9rAdg8FzVWRqqvKCqSwTnU75XKZtzGFHqrMZQxS4dmamvaYkoTZeKUboEnX8rQNNteWjWW3BhcQPWPjcLKB99TESM478e1lvzGbRjUjkOF9jFReNcjebifXKKDBWoCH5mMxGltdbojctmScIN1/UwLlNAIkfFajJ4pB5kaDZ7HeRsjEFEYZ8xnRUtNYE6ElH473V4sCO9aNhbj8U7qBznI7ey+juHX/zzQ3IbOaCdXLOEdGWsWvOLc8=
  template:
    metadata:
      name: redis-auth
      namespace: dev
