redis:
  architecture: standalone

  auth:
    enabled: true
    existingSecret: redis-auth
    existingSecretPasswordKey: redis-password

  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi
