image:
  tag: "sha-2d4cb4b"
  pullPolicy: IfNotPresent
secrets:
  existingSecret: "checkout-bff-secrets"
  redisSecret: "redis-url"
env:
  CHECKOUT_BFF_PORT: "8081"
  NODE_ENV: development
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-alloy.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "checkout-bff"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
