image:
  tag: "sha-2b48f78"
  pullPolicy: IfNotPresent
secrets:
  existingSecret: "orders-api-secrets"
  redisSecret: "redis-url"
env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://+:8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-alloy.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "orders-api"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
