image:
  tag: "latest"
  pullPolicy: Always

secrets:
  existingSecret: "notifier-worker-secrets"
  redisSecret: "redis-url"

env:
  CONSUMER_GROUP: "notifier-workers"
  NOTIFIER_WORKER_PORT: "8082"
  NODE_ENV: development
