apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: checkout-bff-latency
  namespace: monitoring
  labels:
    app.kubernetes.io/name: checkout-bff
    app.kubernetes.io/part-of: polyglot-sre-platform
    pyrra.dev/team: platform
    release: kube-prometheus-stack
spec:
  description: 95% of checkout-bff HTTP requests complete in under 500ms (p95 < 500ms).
  target: "95"
  window: 4w
  indicator:
    latency:
      success:
        metric: http_server_duration_seconds_bucket{job="checkout-bff",le="0.5"}
      total:
        metric: http_server_duration_seconds_count{job="checkout-bff"}
